### PR TITLE
Consistency updates for integration workflow.

### PR DESCRIPTION
**Pull request by beauremus**
These are obvious trivial changes to better align with modern implementations, including access to fermi-ad internal Flutter packages.

### CODE REVIEW

**Comment by beauremus** [comment]
The initial changes address some basic changes.
There are a few things that need to be updated before merging this.

- [ ] How are matrix runs handled?
- [ ] Do we want to `cp` an expected file (include in template)? Or touch .env as in the deployment implementation?

https://github.com/fermi-ad/flutter-template should be updated to match this immediately after this is merged.

**Comment by beauremus** [comment]
https://github.com/skills/reusable-workflows
This gave me the model to understand how the matrix + reusable workflow works.
A single value is passed to the reusable workflow. The parent workflow generates the parallel jobs.

I'm sticking with the `.env` strategy here. Let me know if you think there's a better alternative.

**Comment by beauremus** [comment]
Once this is approved and merged, I can update the template repo, and then we should find which Flutter repos should be updated to use the reusable workflows.

- [ ] Update template repo
- [ ] Update Flutter repos with CI

**Review by cnlklink — APPROVED** [review]

**Review by mgonzal1 — APPROVED** [review]

**Comment by beauremus** [comment]
> > https://github.com/skills/reusable-workflows This gave me the model to understand how the matrix + reusable workflow works. A single value is passed to the reusable workflow. The parent workflow generates the parallel jobs.
> > I'm sticking with the `.env` strategy here. Let me know if you think there's a better alternative.
> 
> what about creating a .env in the repositories with commented lines , showing the variables that should be defined

I tested to see if we could add .env with comments and then also include it in .gitignore, so that no one can accidentally commit and push credentials, but it doesn't work. If you ever add a file to tracking, even if in .gitignore, is always tracked. I think for safety and security we should never allow a .env in our git repos.

I'm open to push back, but I think this is common practice.

**Pull request merged**
